spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexisRodriguezCS/ecommerce-config-repo.git
          clone-on-start: true
          search-paths:
            - 'auth-service'
            - 'inventory-service'
            - 'product-service'
            - 'order-service'
            - 'payment-service'
            - 'notification-service'
          refresh-rate: 0
        default-label: main
      fail-fast: true

  profiles:
    active: git

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
