name: Config Server CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  call-reusable-ci:
    uses: ar-ecommerce-platform/ci-workflows/.github/workflows/ci-template.yml@dev
    with:
      run_integration_tests: false
    secrets:
      #
      REPORTS_TRIGGER_TOKEN: ${{ secrets.REPORTS_TRIGGER_TOKEN }}
      OWASP_API_KEY: ${{ secrets.OWASP_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
