name: Config Server CI

on:
  push:
    branches: [main, develop, test-notify-slack]
  pull_request:
    branches: [main, develop, test-notify-slack]

jobs:
  test-notify-slack:
    uses: ar-ecommerce-platform/ci-workflows/.github/workflows/notify-slack.yml@dev
    with:
      service_name: "config-server"
      image_sha: "ghcr.io/ar-ecommerce-platform/config-server:ci"
      setup_status: "success"
      code_quality_status: "skipped"
      security_scan_status: "skipped"
      unit_tests_status: "skipped"
      integration_tests_status: "skipped"
      quality_scan_status: "skipped"
      docker_release_status: "success"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}