name: Dependency Review

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  call-dependency-review:
    uses: ar-ecommerce-platform/.github/.github/workflows/dependency-review.yml@main
