name: Linting

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  call-lint:
    uses: ar-ecommerce-platform/.github/.github/workflows/lint-template.yml@main
